/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package davidsondps.gui;

/**
 *
 * @author Davidson
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        btmpaciente = new javax.swing.JMenu();
        meuentrarPaciente = new javax.swing.JMenuItem();
        meusairPaciente = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuEntarMedico = new javax.swing.JMenuItem();
        menuSairMedico = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TELA LISTAR MEDICO E PACIENTE");

        btmpaciente.setText("PACIENTE");
        btmpaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmpacienteActionPerformed(evt);
            }
        });

        meuentrarPaciente.setText("ENTRAR");
        meuentrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meuentrarPacienteActionPerformed(evt);
            }
        });
        btmpaciente.add(meuentrarPaciente);

        meusairPaciente.setText("SAIR");
        meusairPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meusairPacienteActionPerformed(evt);
            }
        });
        btmpaciente.add(meusairPaciente);

        jMenuBar1.add(btmpaciente);

        jMenu1.setText("MEDICO");

        menuEntarMedico.setText("ENTRAR");
        menuEntarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEntarMedicoActionPerformed(evt);
            }
        });
        jMenu1.add(menuEntarMedico);

        menuSairMedico.setText("SAIR");
        menuSairMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairMedicoActionPerformed(evt);
            }
        });
        jMenu1.add(menuSairMedico);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(414, 337));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void meuentrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meuentrarPacienteActionPerformed
           Paciente tela = new Paciente ();
        tela.show();
    }//GEN-LAST:event_meuentrarPacienteActionPerformed

    private void meusairPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meusairPacienteActionPerformed
        System.exit(0);
    }//GEN-LAST:event_meusairPacienteActionPerformed

    private void btmpacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmpacienteActionPerformed
System.exit(0);
    }//GEN-LAST:event_btmpacienteActionPerformed

    private void menuEntarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEntarMedicoActionPerformed
    Medico tela = new Medico ();
        tela.show();
    }//GEN-LAST:event_menuEntarMedicoActionPerformed

    private void menuSairMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairMedicoActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSairMedicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btmpaciente;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuEntarMedico;
    private javax.swing.JMenuItem menuSairMedico;
    private javax.swing.JMenuItem meuentrarPaciente;
    private javax.swing.JMenuItem meusairPaciente;
    // End of variables declaration//GEN-END:variables

    private static class TelaCadastro {

        public TelaCadastro() {
        }

        private void show() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }
}
